### ISSUE TITLE
CDA R2 "Extensions"

### ISSUE THREAD

**Issue by fydbill** [MohawkMEDIC/everest#7]
Are the CDA extensions linked below implemented on the Everest framework anyhow? Because I need to use them in a CDA and I seem unable to find them.

http://wiki.hl7.org/index.php?title=CDA_R2_Extensions#Non-HL7_Extensions

**Comment by justin-fyfe** [comment]
They are not, but you can extend the serialization classes to add whatever elements you like to a CDA instance.

Sent from my Windows 10 phone
