### ISSUE TITLE
Virus detected - Solution Items/MARC.Everest.RMIM.UV.NE2008.Phone.dll

### ISSUE THREAD

**Issue by MikeCheel** [MohawkMEDIC/everest#8]
Both Windows Defender (I know) and Kapersky Antivirus are detecting this dll as Trojan:Win32/Rundas.B

Download of the zip is from github today.

![2017-10-17 12_55_18-windows defender security center](https://user-images.githubusercontent.com/2339881/31677996-b2eb82bc-b33a-11e7-81e7-ecad59be5b87.png)

**Comment by justin-fyfe** [comment]
Hi,

We have submitted multiple requests to Kapersky to clear this flag. It is safe to delete this file as it is only needed when compiling the Windows Phone 7 versions of the framework.

Cheers
-Justin

**Comment by MikeCheel** [comment]
Windows is flagging it as well which is how I was first alerted to the issue. I then randomly selected Kapersky online scan to check it a second time and it flagged it as the above mentioned trojan. I also scanned it with ESent and that didn't detect anything.
